services:
  db:
    image: postgres:15-alpine
    container_name: minierp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: minierp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: minierp_backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres123@db:5432/minierp?schema=public
      JWT_SECRET: super_secure_token_secret_for_operational_erp_portal_2026
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma db push && npm run db:seed && node dist/src/server.js"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: minierp_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
